
file:
  upload-dir: ./loads
cors:
  originPatterns: http://localhost:8080,http://localhost:3000
security:
  jwt:
    token:
      secret-key: 53c57
      expire-length: 3600000
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/erudio?useTimezone=true&serverTimezone=UTC
    username: root
    password: rootpassword
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view: false
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
springdoc:
  swagger-ui:
    use-root-path: true
server:
  port: 80
